### PR TITLE
Improve test coverage

### PR DESCRIPTION
**Pull request by srisankethu**
Fixes https://github.com/dfarrell07/puppet-opendaylight/issues/116

Signed-off-by: srisankethu <sanketh.uppalapati@research.iiit.ac.in>

### CODE REVIEW

**Comment by srisankethu** [comment]
The build will pass after #120 is merged

**Comment by dfarrell07** [comment]
I guess we'll need to rebase this on top of #120's changes to .travis.yml to see it run with the new test config. /me notices another advantage of Gerrit web UI over GH, has rebase button

**Comment by srisankethu** [comment]
@dfarrell07 The tests are passing. True, the rebase button is another advantage of using gerrit over github. Good to hear to from you after a long time. Hope you had a great time during your holidays. I have sent you an email to your *redhat* account. Just mentioning if my email goes unnoticed among the pile of unread emails you might be having.

**Comment by dfarrell07** [comment]
@srisankethu w00t for passing tests! Thanks!

> Hope you had a great time during your holidays.

Yes, very nice break. Most of it in Boliva for me. Sorry for abandoning you all for a while. And yes, catching up on code review before I try catching up on emails. ;)

**Comment by dfarrell07** [comment]
This looks perfect, no other feedback. Thanks!

**Comment by srisankethu** [comment]
@dfarrell07 Awesome! Sent you two mails actually. Wanted to discuss about the deployment automation. Answer me when you find time :)

**Pull request merged**
