### PR TITLE
Rakefile: Add Travis-Lint check

### PR DESCRIPTION
**Pull request by srisankethu**
Closes https://github.com/dfarrell07/puppet-opendaylight/issues/85

Signed-off-by: srisankethu <sanketh.uppalapati@research.iiit.ac.in>

### CODE REVIEW

**Comment by dfarrell07** [comment]
Awesome, thanks for the PR. If we add them to the [`test` rake target](https://github.com/dfarrell07/puppet-opendaylight/blob/master/Rakefile#L43) they will be automatically run by `bundle exec rake test`, which is the generic quick-catch-most test we recommend and use in CI.

Unfortunately, we should likely just ignore the Travis CI results at the moment. [See the OpenDaylight Integration/Packaging Trello tracking it](https://trello.com/c/t7tRRRTA/383-get-puppet-odl-ci-working).

**Comment by srisankethu** [comment]
@dfarrell07 I initially wanted to added `travis_lint` rake target to `test`. But I thought since travis is a CI tool it did not seem logical to add it to `test`.

**Comment by srisankethu** [comment]
@dfarrell07 Great! I will look at the issue. I am currently trying a way to get `git-review` work under proxy. I found no articles till now which could help me. Anyway, my semester will end soon and I will be home by Dec4. No proxies there :+1:

**Comment by dfarrell07** [comment]
Okay, cool. Had thought about that too, good either way I guess.

**Pull request merged**
